/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class EchoRustClient {
  constructor(address: string, onReceiveCallback: (err: Error | null, value: string) => any)
  send(message: string): Promise<void>
}
